### ISSUE TITLE
need a working simp_le fork

### ISSUE THREAD

**Issue by JasperWallace** [Boaterfly/ansible-role-simp_le#11]
The acme protocol changed and simp_le is bust,

https://github.com/zenhack/simp_le/ looks ok

**Comment by L-P** [comment]
Thanks!

**Comment by JasperWallace** [comment]
No problem :)

btw, i noticed that the role has disappeared from ansible galaxy, would it be possible to add it back?

Or do you think the role (and simp_le) should be completely depreciated? (In which case I'll find something else and write a migration guide).

**Comment by L-P** [comment]
I added it back (had some weird issues with ansible-galaxy not wanting to register the repo a few months ago, it's fixed now).

I still use this role on a server with no systemd so I would not consider it totally deprecated, I edited the README to reflect this.
