### ISSUE TITLE
Deprecation warning: sudo vs become

### ISSUE THREAD

**Issue by anisse** [Boaterfly/ansible-role-simp_le#9]
When running the playbook, we get this error message:

```

[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and make sure become_method is 'sudo' (default).
This feature                                                                                                                          
 will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.  
```

Maybe it's not the time yet to upgrade to become if you want to support older ansible versions, but it's something to be aware of.
http://docs.ansible.com/ansible/become.html

**Comment by L-P** [comment]
Thanks for the warning. I'm aware of this but was waiting for Ansible
2.0 to reach Ubuntu 16.04.  
Debian is stuck with 1.7 until mid-2017. =/

`become` was introduced in Ansible 1.9 which is the min_version
specified in meta so I guess I can start using it.

**Comment by JasperWallace** [comment]
jessie-backports has ansible 2.1.1.0 fwiw
